#Local Dev Environment Configuration

#Local Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/